lines = []
lines.append('export default function Footer() {')
lines.append('  return (')
lines.append('    <footer className="bg-[#1A1208] border-t border-[#F5F0E8]/8 py-12">')
lines.append('      <div className="max-w-6xl mx-auto px-6">')
lines.append('        <div className="grid md:grid-cols-4 gap-8 mb-10">')
lines.append('          <div className="md:col-span-2">')
lines.append('            <div className="flex items-center gap-2 mb-4">')
lines.append('              <div className="w-8 h-8 rounded-full bg-[#C8923A] flex items-center justify-center">')
lines.append('                <span className="text-[#F5F0E8] text-xs font-mono font-bold">B</span>')
lines.append('              </div>')
lines.append('              <span className="font-display text-xl font-semibold text-[#F5F0E8]">Brewhaus</span>')
lines.append('            </div>')
lines.append('            <p className="text-[#8C7B6B] text-sm leading-relaxed max-w-xs">Specialty coffee, crafted with intention.</p>')
lines.append('            <div className="flex gap-3 mt-5">')
lines.append('              {["IG", "TW", "TK"].map((s) => (')
lines.append('                <' + 'a key={s} href="#" className="w-9 h-9 rounded-full border border-[#F5F0E8]/10 flex items-center justify-center text-[#8C7B6B] hover:border-[#C8923A]/40 hover:text-[#C8923A] transition-all text-xs font-mono">')
lines.append('                  {s}')
lines.append('                </' + 'a>')
lines.append('              ))}')
lines.append('            </div>')
lines.append('          </div>')
lines.append('          <div>')
lines.append('            <div className="text-xs font-mono text-[#8C7B6B] tracking-widest uppercase mb-4">Navigate</div>')
lines.append('            <div className="space-y-2">')
lines.append('              {["Menu", "About", "Testimonials", "Contact"].map((link) => (')
lines.append('                <' + 'a key={link} href={"#" + link.toLowerCase()} className="block text-sm text-[#F5F0E8]/60 hover:text-[#C8923A] transition-colors">')
lines.append('                  {link}')
lines.append('                </' + 'a>')
lines.append('              ))}')
lines.append('            </div>')
lines.append('          </div>')
lines.append('          <div>')
lines.append('            <div className="text-xs font-mono text-[#8C7B6B] tracking-widest uppercase mb-4">Hours</div>')
lines.append('            <div className="space-y-1 text-sm text-[#F5F0E8]/60">')
lines.append('              <div>Mon-Fri: 7AM - 10PM</div>')
lines.append('              <div>Sat-Sun: 8AM - 11PM</div>')
lines.append('              <div className="text-[#C8923A] mt-2 text-xs">Open Today</div>')
lines.append('            </div>')
lines.append('          </div>')
lines.append('        </div>')
lines.append('        <div className="border-t border-[#F5F0E8]/8 pt-6 flex flex-col md:flex-row justify-between gap-2">')
lines.append('          <p className="text-[#8C7B6B] text-xs font-mono">2025 Brewhaus. All rights reserved.</p>')
lines.append('          <p className="text-[#8C7B6B] text-xs font-mono">Made with love in Jakarta</p>')
lines.append('        </div>')
lines.append('      </div>')
lines.append('    </footer>')
lines.append('  )')
lines.append('}')
with open('components/Footer.jsx', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print('Done')
